/**
 * Des: language object
 * created_at: 2023.05.10
 * updated_at: 2023.05.10
 */

const langObj = {
  en: {
    lang: "Language",
    login: "Login",
    loginAs: "LOGIN AS",
    contractor: "Contractor",
    sales: "Salse",
    admin: "Admin",
    homeHeadTitle: "Get paid on time, every time.",
    homeHeadSubTitle1: "For sales and crew teams powered",
    homeHeadSubTitle2: "by United Contractors Roofing",
    welcomeBack: "Welcome back",
    user: "User",
    password: "Password",
    forgotPassword: "Forgot password?",
    rememberMe: "Remember me",
    create: "Create",
    register: "Register",
    name: "Name",
    lastName: "Last Name",
    company: "Company",
    email: "Email",
    mailingAddress: "Mailing Address",
    setYourPassword: "Set your password",
    confirmPassword: "Confirm password",
    phone: "Phone",
    postalCode: "Postal Code",
    createAccount: "Create Account",
    cancel: "Cancel",
    resetYourPassword: "Reset your password",
    resetPassDes: "Enter the email associated with your account and we will send you a link to reset your password.",
    continue: "Continue",
    setYourNewPassword: "Set your new password",
    enterYourNewPassword: "Enter your new password",
    passValid1: "Less than 8 characters.",
    passValid2: "Must more than one special character.",
    invalidEmail: "Invalid Email.",
    invalidPhone: "Must follow the style: (123) 456-7890.",
    notMatchPassword: "Your passwords doesn't match.",
    passValid2: "Must more than one special character.",
    required: "Required.",
    notFindEmail: "We couldn't find an account with that email.",
  },
  sp: {
    lang: "Idioma",
    login: "Iniciar sesión",
    loginAs: "INICIARSESIÓN COMO",
    contractor: "Contratista",
    sales: "Ventas",
    admin: "Admin",
    homeHeadTitle: "Obtenga su pago a tiempo, cada vez.",
    homeHeadSubTitle1: "Para los equipos de ventas y crews.",
    homeHeadSubTitle2: "Respaldado por United Contractors Roofing.",
    welcomeBack: "Bienvenido de nuevo",
    user: "Usuario",
    password: "Contraseña",
    forgotPassword: "¿Has olvidado tu contraseña?",
    rememberMe: "Recuerda me",
    create: "Crear",
    register: "Regístrarse",
    name: "Nombre",
    lastName: "Apellido",
    company: "Compañía",
    email: "Correo",
    mailingAddress: "Dirección de envio",
    setYourPassword: "Establece tu contraseña",
    confirmPassword: "Confirmar Contraseña",
    phone: "Número",
    postalCode: "Código Postal",
    createAccount: "Crear cuenta",
    cancel: "Cancelar",
    resetYourPassword: "Restablecer su contraseña",
    resetPassDes: "Ingrese el correo electrónico asociado con su cuenta y le enviaremos un enlace para restablecer su contraseña.",
    continue: "Continuar",
    setYourNewPassword: "Introduzca su nueva contraseña",
    enterYourNewPassword: "Introduzca su nueva contraseña",
    passValid1: "8 caracteres mínimo.",
    passValid2: "Un carácter especial.",
    invalidEmail: "Email inválido.",
    invalidPhone: "Debe seguir el estilo: (123) 456-7890.",
    notMatchPassword: "Tus contraseñas no coinciden.",
    passValid2: "Debe más de un carácter especial.",
    required: "Requerida.",
    notFindEmail: "No pudimos encontrar una cuenta con ese correo electrónico.",
  },
};

export default langObj;
